// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeS7cVobhjWsyFfGfcBeqRRd1e32IwMAQ',
    appId: '1:619617877781:web:a474b707f74fb6f9e1731c',
    messagingSenderId: '619617877781',
    projectId: 'homework-app-98a84',
    authDomain: 'homework-app-98a84.firebaseapp.com',
    storageBucket: 'homework-app-98a84.appspot.com',
    measurementId: 'G-KVPD1TW387',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCedpdP_hiKs0zKvUdzHKdC3cyS-lc4Vvs',
    appId: '1:619617877781:android:77974d084b3f31c0e1731c',
    messagingSenderId: '619617877781',
    projectId: 'homework-app-98a84',
    storageBucket: 'homework-app-98a84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4aId7jGFTiCeVc4Ny4b9M6yq0ouYMzlU',
    appId: '1:619617877781:ios:186b0330f360c92de1731c',
    messagingSenderId: '619617877781',
    projectId: 'homework-app-98a84',
    storageBucket: 'homework-app-98a84.appspot.com',
    iosBundleId: 'com.example.homeworkAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4aId7jGFTiCeVc4Ny4b9M6yq0ouYMzlU',
    appId: '1:619617877781:ios:ee8584ef3f914975e1731c',
    messagingSenderId: '619617877781',
    projectId: 'homework-app-98a84',
    storageBucket: 'homework-app-98a84.appspot.com',
    iosBundleId: 'com.example.homeworkAi.RunnerTests',
  );
}
